"""Copy the cited pages of the handwritten notes into assets/notes/, web-sized.

The site teaches numbers that were read off handwritten pages (the manual
simulation tables, the chi-square ledger, the GPSS programs). `_source/notes/`
holds those pages, but it is git-ignored on purpose - 12 MB of JPEGs, six times
everything the site needs - so a reader of the site could not check one. This
tool builds the pages the site actually cites into `assets/notes/<id>.jpg`, from
the manifest `data/note_pages.json`, and writes the lookup the page loads:

    python tools/build_note_pages.py            # rebuild every cited page
    python tools/build_note_pages.py --check    # verify only, exit 1 on problems
    python tools/build_note_pages.py --list     # what is declared, with sizes

Only pages named in the manifest are copied: the set is the citation set, not
the notebook. Widening it is a manifest edit plus a rebuild; `--check` fails
when a cited page has no image, when an image has no citation, or when
`data/note_pages.js` no longer matches the manifest. `tools/check_note_pages.js`
holds the other half of the same contract from the content side.

Size is the reason for the resample: the notes render at 1100 px wide and ~200
KB. 1000 px at JPEG q72 keeps handwriting legible (the same page the earlier
passes read page by page) at roughly two thirds of the bytes. Set
PAGE_WIDTH / PAGE_QUALITY here if that ever needs to move; the tool prints the
total it wrote so the cost stays visible.
"""

from __future__ import annotations

import io
import json
import sys
from pathlib import Path

from PIL import Image

from sitelib import ROOT, Reporter, use_utf8_stdout

MANIFEST = ROOT / "data" / "note_pages.json"
GENERATED = ROOT / "data" / "note_pages.js"
OUT_DIR = ROOT / "assets" / "notes"
SRC_DIR = ROOT / "_source" / "notes"

PAGE_WIDTH = 1000
PAGE_QUALITY = 72


def source_path(entry: dict) -> Path:
    """_source/notes/note2_p58.jpg — note2 pages are zero-padded, note1's too."""
    return SRC_DIR / f"note{entry['note']}_p{entry['page']:02d}.jpg"


def out_path(entry: dict) -> Path:
    return OUT_DIR / f"{entry['id']}.jpg"


def load_manifest() -> list[dict]:
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    return data["pages"]


def render(entry: dict) -> int:
    """Write one web-sized page and return its size in bytes."""
    with Image.open(source_path(entry)) as im:
        im = im.convert("RGB")
        if im.width > PAGE_WIDTH:
            height = round(im.height * PAGE_WIDTH / im.width)
            im = im.resize((PAGE_WIDTH, height), Image.LANCZOS)
        buf = io.BytesIO()
        im.save(buf, "JPEG", quality=PAGE_QUALITY, optimize=True, progressive=True)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    payload = buf.getvalue()
    out_path(entry).write_bytes(payload)
    return len(payload)


def generate_js(pages: list[dict]) -> str:
    """data/note_pages.js — the page loads this like data/analysis.js.

    A <script src> rather than a fetch, for the same reason the chapters live in
    script files: the site must work opened straight off the disk.
    """
    rows = ",\n".join(
        '  "{id}": {{ f: "assets/notes/{id}.jpg", t: {title}, p: "{label}" }}'.format(
            id=e["id"],
            title=json.dumps(e["backs"], ensure_ascii=False),
            label=f"n{e['note']} p{e['page']}",
        )
        for e in pages
    )
    return (
        "/* Generated by tools/build_note_pages.py from data/note_pages.json - do not edit.\n"
        "   One entry per cited note page: f is the web-sized scan, t is what the page\n"
        "   backs, p is the label shown on the chip. */\n"
        "window.NOTE_PAGES = {\n" + rows + "\n};\n"
    )


def main() -> int:
    use_utf8_stdout()
    args = sys.argv[1:]
    check_only = "--check" in args
    show_only = "--list" in args
    report = Reporter(width=44)
    pages = load_manifest()

    if show_only:
        total = sum(out_path(e).stat().st_size for e in pages if out_path(e).exists())
        for e in pages:
            f = out_path(e)
            print(f"  {e['id']:<7} {f.stat().st_size // 1024:>4} KB  {e['backs']}" if f.exists()
                  else f"  {e['id']:<7}    -      {e['backs']}  (not built)")
        print(f"\n{len(pages)} cited page(s), {total / 1024 / 1024:.1f} MB on disk")
        return 0

    if check_only:
        total = 0
        for e in pages:
            src, out = source_path(e), out_path(e)
            report.note(f"{e['id']}: source page exists", src.exists())
            report.note(f"{e['id']}: web page built", out.exists())
            if out.exists():
                total += out.stat().st_size
            if not src.exists() or not out.exists():
                continue
            with Image.open(out) as im:
                report.note(f"{e['id']}: width <= {PAGE_WIDTH}", im.width <= PAGE_WIDTH)
            report.note(f"{e['id']}: not stale vs source",
                        out.stat().st_mtime >= src.stat().st_mtime - 1)
        want = generate_js(pages)
        got = GENERATED.read_text(encoding="utf-8") if GENERATED.exists() else ""
        report.note("data/note_pages.js matches the manifest", got == want)
        known = {out_path(e) for e in pages}
        orphans = [p for p in OUT_DIR.glob("*.jpg") if p not in known] if OUT_DIR.exists() else []
        report.note(f"no orphan images ({len(orphans)} found)", not orphans)
        print(f"  total web pages: {total / 1024 / 1024:.1f} MB")
        return report.finish("Note pages: every cited page is built and in sync. OK")

    written = 0
    for e in pages:
        src = source_path(e)
        if not src.exists():
            print(f"  [XX] {e['id']}: {src.relative_to(ROOT)} is missing - cannot build")
            return 1
        written += render(e)
    GENERATED.write_text(generate_js(pages), encoding="utf-8")
    print(f"Built {len(pages)} page(s) into assets/notes/ "
          f"({written / 1024 / 1024:.1f} MB) and regenerated data/note_pages.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
