"""Bundle Inter + JetBrains Mono locally for offline use.

Downloads the variable woff2 subsets (latin, latin-ext, greek) from Google Fonts
and writes assets/fonts/fonts.css with self-hosted @font-face rules.

Run once from the project root:  python freebuff_simulation/tools/fetch_fonts.py
"""

from __future__ import annotations

import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "assets", "fonts")
CSS_PATH = os.path.join(OUT_DIR, "fonts.css")

UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

# family name -> (css2 query, file slug)
FAMILIES = {
    "Inter": ("Inter:wght@100..900", "inter"),
    "JetBrains Mono": ("JetBrains+Mono:wght@100..800", "jetbrains-mono"),
}

# Subsets we actually need: latin for prose, greek for pi / lambda / mu / chi,
# latin-ext for accented names.
SUBSET_MARKERS = [
    ("latin", "U+0000-00FF"),
    ("latin-ext", "U+0100-02BA"),
    # Google's greek block starts at 0370 but lists the sub-ranges individually.
    ("greek", "U+0370-0377"),
]

BLOCK_RE = re.compile(r"@font-face\s*\{(.*?)\}", re.S)


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def pick_subset(unicode_range: str) -> str | None:
    for name, marker in SUBSET_MARKERS:
        if marker in unicode_range:
            return name
    return None


def download(url: str, dest: str) -> int:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        data = resp.read()
    with open(dest, "wb") as fh:
        fh.write(data)
    return len(data)


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    css_parts = [
        "/* Self-hosted fonts bundled for freebuff_simulation.",
        " * Generated by tools/fetch_fonts.py - do not edit by hand.",
        " * Source: Google Fonts (Inter, JetBrains Mono), OFL 1.1.",
        " */",
        "",
    ]
    total = 0
    for family, (query, slug) in FAMILIES.items():
        url = f"https://fonts.googleapis.com/css2?family={query}&display=swap"
        css = fetch(url)
        for block in BLOCK_RE.findall(css):
            weight = re.search(r"font-weight:\s*([^;]+);", block)
            src = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            urange = re.search(r"unicode-range:\s*([^;]+);", block)
            if not (weight and src and urange):
                continue
            subset = pick_subset(urange.group(1))
            if subset is None:
                continue
            weight = weight.group(1).strip()
            filename = f"{slug}-{subset}.woff2"
            size = download(src.group(1), os.path.join(OUT_DIR, filename))
            total += size
            print(f"  {filename:34s} {size / 1024:7.1f} KB  (weight {weight})")
            css_parts.append(
                "@font-face {\n"
                f"  font-family: '{family}';\n"
                "  font-style: normal;\n"
                f"  font-weight: {weight};\n"
                "  font-display: swap;\n"
                f"  src: url('{filename}') format('woff2');\n"
                f"  unicode-range: {urange.group(1).strip()};\n"
                "}\n"
            )

    with open(CSS_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(css_parts))
    print(f"\nTotal {total / 1024:.1f} KB -> {os.path.relpath(CSS_PATH, ROOT)}")


if __name__ == "__main__":
    main()
