#!/usr/bin/env python3
"""Write the service worker that makes a built bundle work offline.

WHY A BUILT BUNDLE NEEDS ONE. Everything that is *content* on this site - eight
chapters, 89 quiz questions, 92 past-question cards with model answers, the mock
exam, the analyses - lives inside `site.js`. So a bundle that is cached once is
the entire course, offline, with no data: the shell needs no server to route, the
hash router needs no server to route it, and the appearance the reader picked is
in localStorage. What is NOT in the shell is the imagery (231 slide images for
DCC, 41 note pages for Simulation, 12 MB between them), so those are cached the
first time they are looked at instead of up front.

Two strategies, and the split is deliberate:

  * NAVIGATIONS go to the network first and fall back to the cached `index.html`.
    Network first because a rebuild must be visible on the next load when there
    IS a network - a cache-first shell pins a stale build for as long as the cache
    lives, which is the failure people actually notice.
  * ASSETS go to the cache first and fill from the network in the background.
    `site.css`, `site.js` and the fonts are content-addressed by the CACHE NAME
    below: the name is a hash of their bytes, so a changed build cannot be served
    from an old cache, and the old one is deleted on activate.

The cache name is therefore not a version number a human maintains. That was the
one bug worth designing out: a hand-bumped `v3` that somebody forgets to bump
ships a site that serves the previous stylesheet to every returning reader, and
nothing about the deploy looks wrong.

    python tools/make_sw.py                 # into dist-dcc/
    python tools/make_sw.py --out dist      # into dist/
    python tools/make_sw.py --check         # fail if the built worker is stale

`tools/build_deploy.py` calls write_worker() itself, for the same reason it writes
the mode sheet: it CLEARS its output directory, so a worker generated outside the
build is deleted by the next build. tools/check_offline.py is the gate step, and
it re-derives the hash from the files on disk.

The registration is not here - it is injected into the bundle's `index.html` by
the build, from the `<!--offline-->` marker each entry page carries. See
`OFFLINE_SNIPPET`. The source pages keep the marker and no worker, because there
is nothing to cache before the build: the source page loads 17 separate scripts.
"""

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Everything the shell needs, in the order it is worth fetching. `theme-sheet.html`
# is optional (it is only there when the build was given --sheet) and is included
# when present so the comparison sheet survives a flight too.
SHELL = ("index.html", "site.css", "site.js", "theme-sheet.html")

# url(...) in the built sheet, which is where the font files are named. Read out
# of the bundle rather than listed here: a fifth family would otherwise be
# discovered by a reader on a plane.
FONT_RE = re.compile(r"""url\(\s*['"]?([^'")]+)['"]?\s*\)""")

# The marker the entry pages carry. The build swaps it for the snippet below.
MARKER = "<!--offline-->"

OFFLINE_SNIPPET = """<script>
/* Offline support. Generated into the bundle by tools/build_deploy.py, which
   replaces the marker comment in the entry page - the source page carries the
   marker and no worker, because there is nothing worth caching before the build:
   that page loads its content as 17 separate blocking scripts. (The marker's own
   text is deliberately not repeated here: this snippet is what replaces it, and
   a copy of it would make "does the bundle still contain the marker?" true
   forever.)

   Registered relative to the page, so the worker's SCOPE is the bundle
   directory and nothing outside it can be intercepted; on GitHub Pages, where
   the bundle lives at /<repo>/, a root-absolute /sw.js would not even exist.

   updateViaCache:'none' is not optional. Pages serves sw.js with its own 10
   minute cache, and the browser re-validates the worker script through the HTTP
   cache by default - so a rebuild could sit unseen for ten minutes on a device
   that has the old worker, which is exactly the device that needs the fix. */
if('serviceWorker' in navigator && (location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1')){
  window.addEventListener('load',function(){
    navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).catch(function(){});
  });
}
</script>"""

# The worker itself. Kept as one string with two slots so that what is checked is
# what is written - tools/check_offline.py reads VERSION and SHELL back out of the
# file on disk, not out of this template.
WORKER = """/* Generated by tools/make_sw.py - do not edit.
   Offline support for a built bundle. The cache name is a hash of the bytes in
   SHELL, so any change to the app produces a new cache and the old one is
   deleted on activate; nothing here needs bumping by hand. */
var VERSION = '%(version)s';
var SHELL = %(shell)s;

self.addEventListener('install', function (event) {
  event.waitUntil((async function () {
    var cache = await caches.open(VERSION);
    /* Individually, not addAll: one 404 in addAll rejects the whole install and
       leaves the device with no worker at all, which is the worst outcome - a
       reader who is told they are offline when they are not. */
    await Promise.all(SHELL.map(function (url) {
      return cache.add(new Request(url, { cache: 'reload' })).catch(function () {});
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', function (event) {
  event.waitUntil((async function () {
    var keys = await caches.keys();
    await Promise.all(keys.map(function (key) {
      return key === VERSION ? null : caches.delete(key);
    }));
    /* claim() so the very first visit is already offline-capable, rather than
       needing a reload before the worker controls anything. */
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', function (event) {
  var request = event.request;
  if (request.method !== 'GET') return;
  var url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    /* Network first, shell second. ignoreSearch because the page may be reached
       through an appearance link (?t=&w=&c=), and that must not miss the cache. */
    event.respondWith((async function () {
      var cached = await caches.match('index.html', { ignoreSearch: true });
      var fresh = null;
      try {
        fresh = await fetch(request);
      } catch (error) {
        fresh = null;              /* no network at all */
      }
      if (fresh && fresh.ok) {
        await cachePut(request, fresh.clone());
        return fresh;
      }
      /* Either the network is gone or the host answered 404 - and this is a
         hash-routed single page, so EVERY navigation belongs to index.html. A
         cached shell is a better answer than a 404 page when the host got the
         path wrong, and the only answer when there is no network. */
      if (cached) return cached;
      if (fresh) return fresh;
      throw new Error('offline with nothing cached');
    })());
    return;
  }

  /* Assets: cache first, fill in the background. Figures and note pages are
     fetched as the reader scrolls, so this is what makes a plane-friendly read
     without pre-downloading 12 MB nobody asked for. */
  event.respondWith((async function () {
    var hit = await caches.match(request, { ignoreSearch: true });
    if (hit) return hit;
    var response = await fetch(request);
    if (response && response.ok && response.type === 'basic') await cachePut(request, response.clone());
    return response;
  })());
});

async function cachePut(request, response) {
  try {
    var cache = await caches.open(VERSION);
    await cache.put(request, response);
  } catch (error) {
    /* A cache that refuses a write (opaque response, quota) must not turn into a
       failed request: the reader gets the bytes either way. */
  }
}
"""


def font_urls(out_dir: Path) -> list[str]:
    """Every url() the built sheet names, as a path from the bundle root."""
    css = out_dir / "site.css"
    if not css.is_file():
        return []
    out = []
    for match in FONT_RE.finditer(css.read_text(encoding="utf-8")):
        url = match.group(1)
        if url.startswith(("http", "//", "data:", "#")) or url.startswith("/"):
            continue
        out.append(url.split("?")[0].split("#")[0])
    # Sorted and de-duplicated: two sheets may name the same file, and the hash
    # below must depend on the SET of files, not on the order they were mentioned.
    return sorted(set(out))


def shell_for(out_dir: Path) -> list[str]:
    urls = [name for name in SHELL if (out_dir / name).is_file()]
    urls += font_urls(out_dir)
    return urls


def version_for(out_dir: Path, urls: list[str]) -> str:
    """A hash of what is being cached - file names AND bytes.

    Names are in the hash so that a build which only drops or adds a file (a
    chapter removed, a font retired) still produces a new cache.
    """
    digest = hashlib.sha256()
    for url in urls:
        path = out_dir / url
        digest.update(url.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes() if path.is_file() else b"<missing>")
        digest.update(b"\0")
    return "offline-" + digest.hexdigest()[:12]


def render(out_dir: Path) -> tuple[str, list[str], str]:
    urls = shell_for(out_dir)
    if "index.html" not in urls or "site.js" not in urls:
        raise SystemExit("make_sw: the output directory has no index.html/site.js "
                         "- build the bundle first")
    version = version_for(out_dir, urls)
    return WORKER % {"version": version, "shell": json.dumps(urls, indent=0)}, urls, version


def write_worker(out_dir: Path) -> int:
    """Write sw.js into a built bundle. 0 on success, 1 on failure."""
    out_dir = Path(out_dir)
    if not out_dir.is_dir():
        print(f"make_sw: {out_dir} does not exist - build the bundle first")
        return 1
    source, urls, version = render(out_dir)
    (out_dir / "sw.js").write_text(source, encoding="utf-8", newline="\n")
    print(f"wrote {out_dir / 'sw.js'} - {version}, {len(urls)} files precached")
    return 0


def check(out_dir: Path) -> int:
    """Re-derive the worker from the bundle and compare. 0 if current."""
    out_dir = Path(out_dir)
    if not out_dir.is_dir():
        print(f"make_sw: {out_dir} does not exist - nothing built to check")
        return 0
    worker = out_dir / "sw.js"
    if not worker.is_file():
        print(f"{worker} is missing - that bundle was not built with tools/build_deploy.py")
        return 1
    # The registration is the half that is easiest to lose silently: a worker with
    # no page registering it is inert, and a page still carrying the marker means
    # the build did not swap it in. Neither shows up in a diff of sw.js.
    page = out_dir / "index.html"
    if page.is_file():
        markdown = page.read_text(encoding="utf-8")
        if MARKER in markdown:
            print(f"{page} still contains {MARKER} - the build did not swap in the "
                  f"registration, so nothing would ever install the worker")
            return 1
        if "serviceWorker.register('sw.js'" not in markdown:
            print(f"{page} does not register sw.js - the worker would never run")
            return 1
    for entry in (ROOT / "index.html", ROOT / "dcc-site" / "index.html"):
        if entry.is_file() and MARKER not in entry.read_text(encoding="utf-8"):
            print(f"{entry} has lost its {MARKER} marker - a source page with no "
                  f"marker builds a bundle with no offline support")
            return 1

    want, urls, version = render(out_dir)
    have = worker.read_text(encoding="utf-8")
    if have != want:
        got = re.search(r"var VERSION = '([^']+)'", have)
        print(f"{worker} is OUT OF DATE")
        print(f"  it caches {got.group(1) if got else '?'}, the bundle hashes to {version}")
        print("  rebuild: python tools/build_deploy.py ... (it writes the worker itself)")
        return 1
    print(f"sw.js is current ({version}, {len(urls)} files precached); "
          f"index.html registers it")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default=str(ROOT / "dist-dcc"),
                    help="the built bundle (default: dist-dcc)")
    ap.add_argument("--check", action="store_true",
                    help="do not write; fail if the built worker disagrees with the bundle")
    args = ap.parse_args()
    out = Path(args.out)
    return check(out) if args.check else write_worker(out)


if __name__ == "__main__":
    sys.exit(main())
